In [13]:
import pandas as pd

In [14]:
df= pd.read_csv("../data/weatherAUS.csv")
df.head()

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,2008-12-01,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,W,...,71.0,22.0,1007.7,1007.1,8.0,NaN,16.9,21.8,No,No
1,2008-12-02,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,NNW,...,44.0,25.0,1010.6,1007.8,NaN,NaN,17.2,24.3,No,No
2,2008-12-03,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,W,...,38.0,30.0,1007.6,1008.7,NaN,2.0,21.0,23.2,No,No
3,2008-12-04,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0,SE,...,45.0,16.0,1017.6,1012.8,NaN,NaN,18.1,26.5,No,No
4,2008-12-05,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0,ENE,...,82.0,33.0,1010.8,1006.0,7.0,8.0,17.8,29.7,No,No

In [15]:
df_raw= df.copy(deep=True)
## create a seperate copy of the original data to avoid any changes to the original data
print("Records", df_raw.shape[0])
## gives the number of Records/rows in the dataset
print("Features",df_raw.shape[1])
#gives the number of Features/columns in the dataset

df_raw.info()
## gives the overall summary of the strucuture

Records 145460
Features 23
<class 'pandas.DataFrame'>
RangeIndex: 145460 entries, 0 to 145459
Data columns (total 23 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Date           145460 non-null  str
 1   Location       145460 non-null  str
 2   MinTemp        143975 non-null  float64
 3   MaxTemp        144199 non-null  float64
 4   Rainfall       142199 non-null  float64
 5   Evaporation    82670 non-null   float64
 6   Sunshine       75625 non-null   float64
 7   WindGustDir    135134 non-null  str
 8   WindGustSpeed  135197 non-null  float64
 9   WindDir9am     134894 non-null  str
 10  WindDir3pm     141232 non-null  str
 11  WindSpeed9am   143693 non-null  float64
 12  WindSpeed3pm   142398 non-null  float64
 13  Humidity9am    142806 non-null  float64
 14  Humidity3pm    140953 non-null  float64
 15  Pressure9am    130395 non-null  float64
 16  Pressure3pm    130432 non-null  float64
 17  Cloud9am       89572 non-null   float64
 18  Cloud3pm       86102 non-null   float64
 19  Temp9am        143693 non-null  float64
 20  Temp3pm        141851 non-null  float64
 21  RainToday      142199 non-null  str
 22  RainTomorrow   142193 non-null  str
dtypes: float64(16), str(7)
memory usage: 25.5 MB

In [16]:
missing_val = df_raw.isna().sum()
#checks every row and column for missing vlaues and then sums them up 

print("COLUMNS With Missing Values")
#heading of the results is printed
print(missing_val[missing_val>0].sort_values(ascending=False))
#checks using the operater condition if the missing values are greater than 0 and then sorts the results in descending order

COLUMNS With Missing Values
Sunshine         69835
Evaporation      62790
Cloud3pm         59358
Cloud9am         55888
Pressure9am      15065
Pressure3pm      15028
WindDir9am       10566
WindGustDir      10326
WindGustSpeed    10263
Humidity3pm       4507
WindDir3pm        4228
Temp3pm           3609
RainTomorrow      3267
Rainfall          3261
RainToday         3261
WindSpeed3pm      3062
Humidity9am       2654
WindSpeed9am      1767
Temp9am           1767
MinTemp           1485
MaxTemp           1261
dtype: int64

In [17]:
missing_percent = df_raw.isna().sum() / len(df_raw) * 100

missing_summary = pd.DataFrame({
    "Missing Values": missing_val,
    "Missing Percentages": missing_percent.round(2)
})

missing_summary = missing_summary[
    missing_summary["Missing Values"] > 0].sort_values(
    "Missing Percentages",
    ascending=False
)

missing_summary

               Missing Values  Missing Percentages
Sunshine                69835                48.01
Evaporation             62790                43.17
Cloud3pm                59358                40.81
Cloud9am                55888                38.42
Pressure9am             15065                10.36
Pressure3pm             15028                10.33
WindDir9am              10566                 7.26
WindGustDir             10326                 7.10
WindGustSpeed           10263                 7.06
Humidity3pm              4507                 3.10
WindDir3pm               4228                 2.91
Temp3pm                  3609                 2.48
RainTomorrow             3267                 2.25
Rainfall                 3261                 2.24
RainToday                3261                 2.24
WindSpeed3pm             3062                 2.11
Humidity9am              2654                 1.82
WindSpeed9am             1767                 1.21
Temp9am                  1767                 1.21
MinTemp                  1485                 1.02
MaxTemp                  1261                 0.87

### Initial Observations for today

In [18]:
duplicated_rows = df_raw.duplicated().sum()
print("Number of duplicated rows:", duplicated_rows)

Number of duplicated rows: 0

In [19]:
numeric_cols = df_raw.select_dtypes(include="number").columns
categorical_cols = df_raw.select_dtypes(include="str").columns

print("Numerical columns:")
print(numeric_cols.tolist())

print("\nCategorical columns:")
print(categorical_cols.tolist())

Numerical columns:
['MinTemp', 'MaxTemp', 'Rainfall', 'Evaporation', 'Sunshine', 'WindGustSpeed', 'WindSpeed9am', 'WindSpeed3pm', 'Humidity9am', 'Humidity3pm', 'Pressure9am', 'Pressure3pm', 'Cloud9am', 'Cloud3pm', 'Temp9am', 'Temp3pm']

Categorical columns:
['Date', 'Location', 'WindGustDir', 'WindDir9am', 'WindDir3pm', 'RainToday', 'RainTomorrow']

In [20]:
df_raw[numeric_cols].describe()

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm
count,143975.000000,144199.000000,142199.000000,82670.000000,75625.000000,135197.000000,143693.000000,142398.000000,142806.000000,140953.000000,130395.00000,130432.000000,89572.000000,86102.000000,143693.000000,141851.00000
mean,12.194034,23.221348,2.360918,5.468232,7.611178,40.035230,14.043426,18.662657,68.880831,51.539116,1017.64994,1015.255889,4.447461,4.509930,16.990631,21.68339
std,6.398495,7.119049,8.478060,4.193704,3.785483,13.607062,8.915375,8.809800,19.029164,20.795902,7.10653,7.037414,2.887159,2.720357,6.488753,6.93665
min,-8.500000,-4.800000,0.000000,0.000000,0.000000,6.000000,0.000000,0.000000,0.000000,0.000000,980.50000,977.100000,0.000000,0.000000,-7.200000,-5.40000
25%,7.600000,17.900000,0.000000,2.600000,4.800000,31.000000,7.000000,13.000000,57.000000,37.000000,1012.90000,1010.400000,1.000000,2.000000,12.300000,16.60000
50%,12.000000,22.600000,0.000000,4.800000,8.400000,39.000000,13.000000,19.000000,70.000000,52.000000,1017.60000,1015.200000,5.000000,5.000000,16.700000,21.10000
75%,16.900000,28.200000,0.800000,7.400000,10.600000,48.000000,19.000000,24.000000,83.000000,66.000000,1022.40000,1020.000000,7.000000,7.000000,21.600000,26.40000
max,33.900000,48.100000,371.000000,145.000000,14.500000,135.000000,130.000000,87.000000,100.000000,100.000000,1041.00000,1039.600000,9.000000,9.000000,40.200000,46.70000

In [21]:
missing_values = df_raw.isnull().sum()

missing_values = missing_values[missing_values > 0].sort_values(ascending=False)

print("Missing values:")
print("\n" + missing_values.to_string())

Missing values:

Sunshine         69835
Evaporation      62790
Cloud3pm         59358
Cloud9am         55888
Pressure9am      15065
Pressure3pm      15028
WindDir9am       10566
WindGustDir      10326
WindGustSpeed    10263
Humidity3pm       4507
WindDir3pm        4228
Temp3pm           3609
RainTomorrow      3267
Rainfall          3261
RainToday         3261
WindSpeed3pm      3062
Humidity9am       2654
WindSpeed9am      1767
Temp9am           1767
MinTemp           1485
MaxTemp           1261

In [22]:
#Target Variable Analysis

#this will count the number of yes, no aswell as the missing values and save the result to target_counts

target_counts = df_raw["RainTomorrow"].value_counts(dropna=False)

print("RainTomorrow distribution:")
print(target_counts)

RainTomorrow distribution:
RainTomorrow
No     110316
Yes     31877
NaN      3267
Name: count, dtype: int64

In [23]:
#does simliar things but instead og dislaing the number of rows it diplays the percetnage of the dataset
target_percent = df_raw["RainTomorrow"].value_counts(
    normalize=True,
    dropna=False
) * 100

print("\nRainTomorrow percentages:")
print(target_percent.round(2))

#inspecting the RainToday column
print("\nRainToday distribution:")
print(df_raw["RainToday"].value_counts(dropna=False))

RainTomorrow percentages:
RainTomorrow
No     75.84
Yes    21.91
NaN     2.25
Name: proportion, dtype: float64

RainToday distribution:
RainToday
No     110319
Yes     31880
NaN      3261
Name: count, dtype: int64

In [24]:
correlation_matrix = df_raw[numeric_cols].corr()

print(correlation_matrix.round(2))

print(
    df_raw.groupby("RainTomorrow")["Rainfall"].describe()
)

               MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
MinTemp           1.00     0.74      0.10         0.47      0.07
MaxTemp           0.74     1.00     -0.07         0.59      0.47
Rainfall          0.10    -0.07      1.00        -0.06     -0.23
Evaporation       0.47     0.59     -0.06         1.00      0.37
Sunshine          0.07     0.47     -0.23         0.37      1.00
WindGustSpeed     0.18     0.07      0.13         0.20     -0.03
WindSpeed9am      0.18     0.01      0.09         0.19      0.01
WindSpeed3pm      0.18     0.05      0.06         0.13      0.05
Humidity9am      -0.23    -0.50      0.22        -0.50     -0.49
Humidity3pm       0.01    -0.51      0.26        -0.39     -0.63
Pressure9am      -0.45    -0.33     -0.17        -0.27      0.04
Pressure3pm      -0.46    -0.43     -0.13        -0.29     -0.02
Cloud9am          0.08    -0.29      0.20        -0.18     -0.68
Cloud3pm          0.02    -0.28      0.17        -0.18     -0.70
Temp9am           0.90     0.89      0.01         0.55      0.29
Temp3pm           0.71     0.98     -0.08         0.57      0.49

               WindGustSpeed  WindSpeed9am  WindSpeed3pm  Humidity9am  \
MinTemp                 0.18          0.18          0.18        -0.23
MaxTemp                 0.07          0.01          0.05        -0.50
Rainfall                0.13          0.09          0.06         0.22
Evaporation             0.20          0.19          0.13        -0.50
Sunshine               -0.03          0.01          0.05        -0.49
WindGustSpeed           1.00          0.61          0.69        -0.22
WindSpeed9am            0.61          1.00          0.52        -0.27
WindSpeed3pm            0.69          0.52          1.00        -0.15
Humidity9am            -0.22         -0.27         -0.15         1.00
Humidity3pm            -0.03         -0.03          0.02         0.67
Pressure9am            -0.46         -0.23         -0.30         0.14
Pressure3pm            -0.41         -0.18         -0.26         0.19
Cloud9am                0.07          0.03          0.05         0.45
Cloud3pm                0.11          0.05          0.03         0.36
Temp9am                 0.15          0.13          0.16        -0.47
Temp3pm                 0.03          0.00          0.03        -0.50

               Humidity3pm  Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  \
MinTemp               0.01        -0.45        -0.46      0.08      0.02
MaxTemp              -0.51        -0.33        -0.43     -0.29     -0.28
Rainfall              0.26        -0.17        -0.13      0.20      0.17
Evaporation          -0.39        -0.27        -0.29     -0.18     -0.18
Sunshine             -0.63         0.04        -0.02     -0.68     -0.70
WindGustSpeed        -0.03        -0.46        -0.41      0.07      0.11
WindSpeed9am         -0.03        -0.23        -0.18      0.03      0.05
WindSpeed3pm          0.02        -0.30        -0.26      0.05      0.03
Humidity9am           0.67         0.14         0.19      0.45      0.36
Humidity3pm           1.00        -0.03         0.05      0.52      0.52
Pressure9am          -0.03         1.00         0.96     -0.13     -0.15
Pressure3pm           0.05         0.96         1.00     -0.06     -0.08
Cloud9am              0.52        -0.13        -0.06      1.00      0.60
Cloud3pm              0.52        -0.15        -0.08      0.60      1.00
Temp9am              -0.22        -0.42        -0.47     -0.14     -0.13
Temp3pm              -0.56        -0.29        -0.39     -0.30     -0.32

               Temp9am  Temp3pm
MinTemp           0.90     0.71
MaxTemp           0.89     0.98
Rainfall          0.01    -0.08
Evaporation       0.55     0.57
Sunshine          0.29     0.49
WindGustSpeed     0.15     0.03
WindSpeed9am      0.13     0.00
WindSpeed3pm      0.16     0.03
Humidity9am      -0.47    -0.50
Humidity3pm      -0.22    -0.56
Pressure9am      -0.42    -0.29
Pressure3pm      -0.47    -0.39
Cloud9am         -0.14    -0.30
Cloud3pm         -0.13    -0.32
Temp9am           1.00     0.86
Temp3pm           0.86     1.00
                 count      mean        std  min  25%  50%  75%    max
RainTomorrow
No            109586.0  1.270290   5.332200  0.0  0.0  0.0  0.2  240.0
Yes            31201.0  6.142104  14.318292  0.0  0.0  0.8  6.2  371.0