In [1]:
import pandas as pd

In [2]:
df= pd.read_csv("../data/weatherAUS.csv")
df.head()

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,2008-12-01,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,W,...,71.0,22.0,1007.7,1007.1,8.0,NaN,16.9,21.8,No,No
1,2008-12-02,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,NNW,...,44.0,25.0,1010.6,1007.8,NaN,NaN,17.2,24.3,No,No
2,2008-12-03,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,W,...,38.0,30.0,1007.6,1008.7,NaN,2.0,21.0,23.2,No,No
3,2008-12-04,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0,SE,...,45.0,16.0,1017.6,1012.8,NaN,NaN,18.1,26.5,No,No
4,2008-12-05,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0,ENE,...,82.0,33.0,1010.8,1006.0,7.0,8.0,17.8,29.7,No,No

In [3]:
df_raw= df.copy(deep=True)
## create a seperate copy of the original data to avoid any changes to the original data
print("Records", df_raw.shape[0])
## gives the number of Records/rows in the dataset
print("Features",df_raw.shape[1])
#gives the number of Features/columns in the dataset

df_raw.info()
## gives the overall summary of the strucuture

Records 145460
Features 23
<class 'pandas.DataFrame'>
RangeIndex: 145460 entries, 0 to 145459
Data columns (total 23 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Date           145460 non-null  str
 1   Location       145460 non-null  str
 2   MinTemp        143975 non-null  float64
 3   MaxTemp        144199 non-null  float64
 4   Rainfall       142199 non-null  float64
 5   Evaporation    82670 non-null   float64
 6   Sunshine       75625 non-null   float64
 7   WindGustDir    135134 non-null  str
 8   WindGustSpeed  135197 non-null  float64
 9   WindDir9am     134894 non-null  str
 10  WindDir3pm     141232 non-null  str
 11  WindSpeed9am   143693 non-null  float64
 12  WindSpeed3pm   142398 non-null  float64
 13  Humidity9am    142806 non-null  float64
 14  Humidity3pm    140953 non-null  float64
 15  Pressure9am    130395 non-null  float64
 16  Pressure3pm    130432 non-null  float64
 17  Cloud9am       89572 non-null   float64
 18  Cloud3pm       86102 non-null   float64
 19  Temp9am        143693 non-null  float64
 20  Temp3pm        141851 non-null  float64
 21  RainToday      142199 non-null  str
 22  RainTomorrow   142193 non-null  str
dtypes: float64(16), str(7)
memory usage: 25.5 MB

In [4]:
missing_val = df_raw.isna().sum()
#checks every row and column for missing vlaues and then sums them up 

print("COLUMNS With Missing Values")
#heading of the results is printed
print(missing_val[missing_val>0].sort_values(ascending=False))
#checks using the operater condition if the missing values are greater than 0 and then sorts the results in descending order

COLUMNS With Missing Values
Sunshine         69835
Evaporation      62790
Cloud3pm         59358
Cloud9am         55888
Pressure9am      15065
Pressure3pm      15028
WindDir9am       10566
WindGustDir      10326
WindGustSpeed    10263
Humidity3pm       4507
WindDir3pm        4228
Temp3pm           3609
RainTomorrow      3267
Rainfall          3261
RainToday         3261
WindSpeed3pm      3062
Humidity9am       2654
WindSpeed9am      1767
Temp9am           1767
MinTemp           1485
MaxTemp           1261
dtype: int64

In [5]:
missing_percent = df_raw.isna().sum() / len(df_raw) * 100

missing_summary = pd.DataFrame({
    "Missing Values": missing_val,
    "Missing Percentages": missing_percent.round(2)
})

missing_summary = missing_summary[
    missing_summary["Missing Values"] > 0].sort_values(
    "Missing Percentages",
    ascending=False
)

missing_summary

               Missing Values  Missing Percentages
Sunshine                69835                48.01
Evaporation             62790                43.17
Cloud3pm                59358                40.81
Cloud9am                55888                38.42
Pressure9am             15065                10.36
Pressure3pm             15028                10.33
WindDir9am              10566                 7.26
WindGustDir             10326                 7.10
WindGustSpeed           10263                 7.06
Humidity3pm              4507                 3.10
WindDir3pm               4228                 2.91
Temp3pm                  3609                 2.48
RainTomorrow             3267                 2.25
Rainfall                 3261                 2.24
RainToday                3261                 2.24
WindSpeed3pm             3062                 2.11
Humidity9am              2654                 1.82
WindSpeed9am             1767                 1.21
Temp9am                  1767                 1.21
MinTemp                  1485                 1.02
MaxTemp                  1261                 0.87

### Initial Observations for today

In [6]:
duplicated_rows = df_raw.duplicated().sum()
print("Number of duplicated rows:", duplicated_rows)

Number of duplicated rows: 0

In [7]:
numeric_cols = df_raw.select_dtypes(include="number").columns
categorical_cols = df_raw.select_dtypes(include="str").columns

print("Numerical columns:")
print(numeric_cols.tolist())

print("\nCategorical columns:")
print(categorical_cols.tolist())

Numerical columns:
['MinTemp', 'MaxTemp', 'Rainfall', 'Evaporation', 'Sunshine', 'WindGustSpeed', 'WindSpeed9am', 'WindSpeed3pm', 'Humidity9am', 'Humidity3pm', 'Pressure9am', 'Pressure3pm', 'Cloud9am', 'Cloud3pm', 'Temp9am', 'Temp3pm']

Categorical columns:
['Date', 'Location', 'WindGustDir', 'WindDir9am', 'WindDir3pm', 'RainToday', 'RainTomorrow']

In [8]:
df_raw[numeric_cols].describe()

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm
count,143975.000000,144199.000000,142199.000000,82670.000000,75625.000000,135197.000000,143693.000000,142398.000000,142806.000000,140953.000000,130395.00000,130432.000000,89572.000000,86102.000000,143693.000000,141851.00000
mean,12.194034,23.221348,2.360918,5.468232,7.611178,40.035230,14.043426,18.662657,68.880831,51.539116,1017.64994,1015.255889,4.447461,4.509930,16.990631,21.68339
std,6.398495,7.119049,8.478060,4.193704,3.785483,13.607062,8.915375,8.809800,19.029164,20.795902,7.10653,7.037414,2.887159,2.720357,6.488753,6.93665
min,-8.500000,-4.800000,0.000000,0.000000,0.000000,6.000000,0.000000,0.000000,0.000000,0.000000,980.50000,977.100000,0.000000,0.000000,-7.200000,-5.40000
25%,7.600000,17.900000,0.000000,2.600000,4.800000,31.000000,7.000000,13.000000,57.000000,37.000000,1012.90000,1010.400000,1.000000,2.000000,12.300000,16.60000
50%,12.000000,22.600000,0.000000,4.800000,8.400000,39.000000,13.000000,19.000000,70.000000,52.000000,1017.60000,1015.200000,5.000000,5.000000,16.700000,21.10000
75%,16.900000,28.200000,0.800000,7.400000,10.600000,48.000000,19.000000,24.000000,83.000000,66.000000,1022.40000,1020.000000,7.000000,7.000000,21.600000,26.40000
max,33.900000,48.100000,371.000000,145.000000,14.500000,135.000000,130.000000,87.000000,100.000000,100.000000,1041.00000,1039.600000,9.000000,9.000000,40.200000,46.70000

In [9]:
missing_values = df_raw.isnull().sum()

missing_values = missing_values[missing_values > 0].sort_values(ascending=False)

print("Missing values:")
print("\n" + missing_values.to_string())

print("Missing values percentage:")
missing_percentage = (missing_values / len(df_raw)) * 100
print("\n" + missing_percentage.to_string())

Missing values:

Sunshine         69835
Evaporation      62790
Cloud3pm         59358
Cloud9am         55888
Pressure9am      15065
Pressure3pm      15028
WindDir9am       10566
WindGustDir      10326
WindGustSpeed    10263
Humidity3pm       4507
WindDir3pm        4228
Temp3pm           3609
RainTomorrow      3267
Rainfall          3261
RainToday         3261
WindSpeed3pm      3062
Humidity9am       2654
WindSpeed9am      1767
Temp9am           1767
MinTemp           1485
MaxTemp           1261
Missing values percentage:

Sunshine         48.009762
Evaporation      43.166506
Cloud3pm         40.807095
Cloud9am         38.421559
Pressure9am      10.356799
Pressure3pm      10.331363
WindDir9am        7.263853
WindGustDir       7.098859
WindGustSpeed     7.055548
Humidity3pm       3.098446
WindDir3pm        2.906641
Temp3pm           2.481094
RainTomorrow      2.245978
Rainfall          2.241853
RainToday         2.241853
WindSpeed3pm      2.105046
Humidity9am       1.824557
WindSpeed9am      1.214767
Temp9am           1.214767
MinTemp           1.020899
MaxTemp           0.866905

In [10]:
#Target Variable Analysis

#this will count the number of yes, no aswell as the missing values and save the result to target_counts

target_counts = df_raw["RainTomorrow"].value_counts(dropna=False)

print("RainTomorrow distribution:")
print(target_counts)

RainTomorrow distribution:
RainTomorrow
No     110316
Yes     31877
NaN      3267
Name: count, dtype: int64

In [11]:
#does simliar things but instead og dislaing the number of rows it diplays the percetnage of the dataset
target_percent = df_raw["RainTomorrow"].value_counts(
    normalize=True,
    dropna=False
) * 100

print("\nRainTomorrow percentages:")
print(target_percent.round(2))

#inspecting the RainToday column
print("\nRainToday distribution:")
print(df_raw["RainToday"].value_counts(dropna=False))

RainTomorrow percentages:
RainTomorrow
No     75.84
Yes    21.91
NaN     2.25
Name: proportion, dtype: float64

RainToday distribution:
RainToday
No     110319
Yes     31880
NaN      3261
Name: count, dtype: int64

In [12]:
correlation_matrix = df_raw[numeric_cols].corr()

print(correlation_matrix.round(2))

print(
    df_raw.groupby("RainTomorrow")["Rainfall"].describe()
)

               MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
MinTemp           1.00     0.74      0.10         0.47      0.07
MaxTemp           0.74     1.00     -0.07         0.59      0.47
Rainfall          0.10    -0.07      1.00        -0.06     -0.23
Evaporation       0.47     0.59     -0.06         1.00      0.37
Sunshine          0.07     0.47     -0.23         0.37      1.00
WindGustSpeed     0.18     0.07      0.13         0.20     -0.03
WindSpeed9am      0.18     0.01      0.09         0.19      0.01
WindSpeed3pm      0.18     0.05      0.06         0.13      0.05
Humidity9am      -0.23    -0.50      0.22        -0.50     -0.49
Humidity3pm       0.01    -0.51      0.26        -0.39     -0.63
Pressure9am      -0.45    -0.33     -0.17        -0.27      0.04
Pressure3pm      -0.46    -0.43     -0.13        -0.29     -0.02
Cloud9am          0.08    -0.29      0.20        -0.18     -0.68
Cloud3pm          0.02    -0.28      0.17        -0.18     -0.70
Temp9am           0.90     0.89      0.01         0.55      0.29
Temp3pm           0.71     0.98     -0.08         0.57      0.49

               WindGustSpeed  WindSpeed9am  WindSpeed3pm  Humidity9am  \
MinTemp                 0.18          0.18          0.18        -0.23
MaxTemp                 0.07          0.01          0.05        -0.50
Rainfall                0.13          0.09          0.06         0.22
Evaporation             0.20          0.19          0.13        -0.50
Sunshine               -0.03          0.01          0.05        -0.49
WindGustSpeed           1.00          0.61          0.69        -0.22
WindSpeed9am            0.61          1.00          0.52        -0.27
WindSpeed3pm            0.69          0.52          1.00        -0.15
Humidity9am            -0.22         -0.27         -0.15         1.00
Humidity3pm            -0.03         -0.03          0.02         0.67
Pressure9am            -0.46         -0.23         -0.30         0.14
Pressure3pm            -0.41         -0.18         -0.26         0.19
Cloud9am                0.07          0.03          0.05         0.45
Cloud3pm                0.11          0.05          0.03         0.36
Temp9am                 0.15          0.13          0.16        -0.47
Temp3pm                 0.03          0.00          0.03        -0.50

               Humidity3pm  Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  \
MinTemp               0.01        -0.45        -0.46      0.08      0.02
MaxTemp              -0.51        -0.33        -0.43     -0.29     -0.28
Rainfall              0.26        -0.17        -0.13      0.20      0.17
Evaporation          -0.39        -0.27        -0.29     -0.18     -0.18
Sunshine             -0.63         0.04        -0.02     -0.68     -0.70
WindGustSpeed        -0.03        -0.46        -0.41      0.07      0.11
WindSpeed9am         -0.03        -0.23        -0.18      0.03      0.05
WindSpeed3pm          0.02        -0.30        -0.26      0.05      0.03
Humidity9am           0.67         0.14         0.19      0.45      0.36
Humidity3pm           1.00        -0.03         0.05      0.52      0.52
Pressure9am          -0.03         1.00         0.96     -0.13     -0.15
Pressure3pm           0.05         0.96         1.00     -0.06     -0.08
Cloud9am              0.52        -0.13        -0.06      1.00      0.60
Cloud3pm              0.52        -0.15        -0.08      0.60      1.00
Temp9am              -0.22        -0.42        -0.47     -0.14     -0.13
Temp3pm              -0.56        -0.29        -0.39     -0.30     -0.32

               Temp9am  Temp3pm
MinTemp           0.90     0.71
MaxTemp           0.89     0.98
Rainfall          0.01    -0.08
Evaporation       0.55     0.57
Sunshine          0.29     0.49
WindGustSpeed     0.15     0.03
WindSpeed9am      0.13     0.00
WindSpeed3pm      0.16     0.03
Humidity9am      -0.47    -0.50
Humidity3pm      -0.22    -0.56
Pressure9am      -0.42    -0.29
Pressure3pm      -0.47    -0.39
Cloud9am         -0.14    -0.30
Cloud3pm         -0.13    -0.32
Temp9am           1.00     0.86
Temp3pm           0.86     1.00
                 count      mean        std  min  25%  50%  75%    max
RainTomorrow
No            109586.0  1.270290   5.332200  0.0  0.0  0.0  0.2  240.0
Yes            31201.0  6.142104  14.318292  0.0  0.0  0.8  6.2  371.0

In [13]:
sunshine_missing_percent = (
    df_raw["Sunshine"]
    .isna()
    .groupby(df_raw["Location"])
    .mean()
    * 100
)

sunshine_missing_percent = sunshine_missing_percent.sort_values(ascending=False)

print("Percentage of missing Sunshine values by Location:")
print(sunshine_missing_percent)

Percentage of missing Sunshine values by Location:
Location
Albury              100.000000
GoldCoast           100.000000
BadgerysCreek       100.000000
Bendigo             100.000000
Ballarat            100.000000
Katherine           100.000000
Wollongong          100.000000
Walpole             100.000000
Uluru               100.000000
Richmond            100.000000
SalmonGums          100.000000
Penrith             100.000000
NorahHead           100.000000
Nhil                100.000000
MountGinini         100.000000
Newcastle           100.000000
Launceston          100.000000
Tuggeranong         100.000000
Witchcliffe         100.000000
Cobar                81.721502
Canberra             55.733411
Williamtown          54.968428
CoffsHarbour         50.348953
Adelaide             44.597557
Sale                 39.581256
Woomera              33.300100
Moree                31.704885
AliceSprings         17.105263
Albany               17.105263
Cairns               15.657895
Portland             14.722499
Dartmoor             14.722499
NorfolkIsland        14.589565
MountGambier         14.572368
WaggaWagga           14.423396
Townsville           13.914474
Nuriootpa             5.350615
Mildura               4.420073
Brisbane              1.534607
SydneyAirport         0.531738
Sydney                0.478469
Hobart                0.438459
PearceRAAF            0.166168
PerthAirport          0.166168
Perth                 0.156593
Darwin                0.125274
MelbourneAirport      0.033234
Watsonia              0.033234
Melbourne             0.031319
Name: Sunshine, dtype: float64

In [14]:
#missing values in evaporation by location
evaporation_missing_percent = (df_raw["Evaporation"].isna().groupby(df_raw["Location"]).mean() * 100).sort_values(ascending=False)

print("Percentage of missing Evaporation values by Location:")
print(evaporation_missing_percent)

Percentage of missing Evaporation values by Location:
Location
Albury              100.000000
Ballarat            100.000000
BadgerysCreek       100.000000
GoldCoast           100.000000
PearceRAAF          100.000000
Witchcliffe         100.000000
Wollongong          100.000000
Walpole             100.000000
Uluru               100.000000
SalmonGums          100.000000
Tuggeranong         100.000000
Penrith             100.000000
MountGinini         100.000000
Nhil                100.000000
NorahHead           100.000000
Newcastle           100.000000
Launceston           95.361842
Bendigo              61.019737
Canberra             46.682189
Adelaide             46.633260
Richmond             46.028581
CoffsHarbour         40.677966
Sale                 39.049518
Williamtown          35.327351
Moree                23.828514
Woomera              14.589565
Dartmoor             13.592556
Portland             13.592556
MountGambier         13.486842
Cairns               12.171053
Cobar                11.399136
Albany                9.539474
NorfolkIsland         7.776670
AliceSprings          7.072368
Katherine             5.893536
WaggaWagga            4.586241
Nuriootpa             4.054503
Mildura               3.888335
Townsville            2.993421
Darwin                1.691199
SydneyAirport         1.528747
Sydney                1.525120
Brisbane              0.595052
Hobart                0.219230
MelbourneAirport      0.099701
Watsonia              0.099701
Melbourne             0.093956
PerthAirport          0.033234
Perth                 0.031319
Name: Evaporation, dtype: float64

In [15]:
missing_percent_by_location = df_raw.groupby("Location").apply(
    lambda x: x.isnull().mean() * 100
)

print("Percentage of missing values by Location:")
print(missing_percent_by_location)

high_missing_locations = missing_percent_by_location[
    (missing_percent_by_location > 70).any(axis=1)
].index.tolist()

print(high_missing_locations)
print(f"Number of locations with high missing values: {len(high_missing_locations)}")
number_of_rows_with_high_missing_values = df_raw[df_raw["Location"].isin(high_missing_locations)].shape[0]
print(f"Number of rows with high missing values: {number_of_rows_with_high_missing_values}")

Percentage of missing values by Location:
                  Date    MinTemp    MaxTemp   Rainfall  Evaporation  \
Location
Adelaide           0.0   0.062637   0.093956   3.194488    46.633260
Albany             0.0   2.072368   1.776316   0.789474     9.539474
Albury             0.0   0.361842   0.361842   0.953947   100.000000
AliceSprings       0.0   0.032895   0.065789   0.263158     7.072368
BadgerysCreek      0.0   1.196411   0.963775   2.691924   100.000000
Ballarat           0.0   0.032895   0.032895   0.394737   100.000000
Bendigo            0.0   0.065789   0.164474   0.197368    61.019737
Brisbane           0.0   0.281867   0.438459   1.002192     0.595052
Cairns             0.0   0.032895   0.000000   1.710526    12.171053
Canberra           0.0   0.174622   0.087311   0.523865    46.682189
Cobar              0.0   0.199402   0.099701   0.697906    11.399136
CoffsHarbour       0.0   0.498504   0.631439   1.861083    40.677966
Dartmoor           0.0   2.293121   2.093719   2.226653    13.592556
Darwin             0.0   0.031319   0.031319   0.000000     1.691199
GoldCoast          0.0   0.098684   0.230263   1.973684   100.000000
Hobart             0.0   0.000000   0.031319   0.156593     0.219230
Katherine          0.0   3.105196   2.534854   1.140684     5.893536
Launceston         0.0   0.197368   0.197368   0.394737    95.361842
Melbourne          0.0  15.032884  15.064203  23.739430     0.093956
MelbourneAirport   0.0   0.000000   0.000000   0.000000     0.099701
Mildura            0.0   0.000000   0.000000   0.066467     3.888335
Moree              0.0   0.066467   0.000000   5.151213    23.828514
MountGambier       0.0   0.065789   0.164474   0.296053    13.486842
MountGinini        0.0   2.993421   1.743421   4.375000   100.000000
Newcastle          0.0  11.385324   7.732807   2.764067   100.000000
Nhil               0.0   0.316857   0.380228   0.570342   100.000000
NorahHead          0.0   0.998668   0.998668   2.496671   100.000000
NorfolkIsland      0.0   0.033234   0.033234   1.495513     7.776670
Nuriootpa          0.0   0.365570   0.299103   0.199402     4.054503
PearceRAAF         0.0   0.731140   0.697906   8.208707   100.000000
Penrith            0.0   0.921356   0.822639   2.467917   100.000000
Perth              0.0   0.000000   0.031319   0.000000     0.031319
PerthAirport       0.0   0.000000   0.000000   0.000000     0.033234
Portland           0.0   0.299103   0.033234   0.432037    13.592556
Richmond           0.0   0.664673   0.465271   1.927551    46.028581
Sale               0.0   0.033234   0.033234   0.299103    39.049518
SalmonGums         0.0   1.366211   1.332889   1.532822   100.000000
Sydney             0.0   0.119617   0.059809   0.209330     1.525120
SydneyAirport      0.0   0.033234   0.000000   0.132935     1.528747
Townsville         0.0   0.065789   0.032895   0.230263     2.993421
Tuggeranong        0.0   0.032906   0.131622   1.349128   100.000000
Uluru              0.0   2.217997   0.443599   3.548796   100.000000
WaggaWagga         0.0   0.000000   0.000000   1.096710     4.586241
Walpole            0.0   1.164338   1.297405   6.220892   100.000000
Watsonia           0.0   0.232635   0.000000   0.332336     0.099701
Williamtown        0.0   0.066467   0.099701  15.154536    35.327351
Witchcliffe        0.0   0.299103   0.199402   1.894317   100.000000
Wollongong         0.0   0.493421   0.361842   1.907895   100.000000
Woomera            0.0   0.132935   0.099701   0.598205    14.589565

                    Sunshine  WindGustDir  WindGustSpeed  WindDir9am  \
Location
Adelaide           44.597557     0.814281       0.814281    8.581272
Albany             17.105263   100.000000     100.000000    8.125000
Albury            100.000000     1.052632       1.052632   17.269737
AliceSprings       17.105263     1.677632       1.677632    7.565789
BadgerysCreek     100.000000     2.525756       2.525756   14.456630
Ballarat          100.000000     1.019737       1.019737    2.993421
Bendigo           100.000000     1.348684       1.315789    8.026316
Brisbane            1.534607     1.284059       1.284059    2.192296
Cairns             15.657895     0.625000       0.592105    1.414474
Canberra           55.733411     9.866123       9.807916   15.745052
Cobar              81.721502     1.395813       1.395813    0.897308
CoffsHarbour       50.348953    11.930874      11.930874   11.532070
Dartmoor           14.722499     2.293121       2.293121   18.876703
Darwin              0.125274     1.440651       1.315377    0.876918
GoldCoast         100.000000     3.947368       3.947368    2.138158
Hobart              0.438459     0.720326       0.720326    1.284059
Katherine         100.000000     1.837769       1.837769    2.534854
Launceston        100.000000     1.118421       1.085526   15.131579
Melbourne           0.031319     0.438459       0.438459    1.565925
MelbourneAirport    0.033234     0.498504       0.498504    1.329345
Mildura             4.420073     0.166168       0.166168    3.057494
Moree              31.704885     2.592223       2.558990    3.589232
MountGambier       14.572368     1.743421       1.710526    2.763158
MountGinini       100.000000    10.493421      10.493421    8.223684
Newcastle         100.000000   100.000000     100.000000   46.758802
Nhil              100.000000     0.697085       0.697085    3.168568
NorahHead         100.000000     1.797603       1.797603    3.561917
NorfolkIsland      14.589565     1.495513       1.462280    1.030243
Nuriootpa           5.350615     1.628448       1.129944    4.785643
PearceRAAF          0.166168     4.818877       4.818877    3.024261
Penrith           100.000000     2.138861       2.138861   18.394209
Perth               0.156593     0.156593       0.156593    4.196680
PerthAirport        0.166168     1.528747       1.528747    1.329345
Portland           14.722499     1.163177       1.163177    2.326354
Richmond          100.000000     1.894317       1.827850   28.348288
Sale               39.581256     4.685942       4.685942    2.725158
SalmonGums        100.000000     2.799067       2.799067    3.298900
Sydney              0.478469    31.040670      31.040670    1.674641
SydneyAirport       0.531738     1.694915       1.694915    0.265869
Townsville         13.914474     0.756579       0.756579    4.046053
Tuggeranong       100.000000     1.382034       1.382034   21.224087
Uluru             100.000000     3.422053       3.422053    4.182510
WaggaWagga         14.423396     0.930542       0.930542    3.954802
Walpole           100.000000     3.925482       2.860945    9.514305
Watsonia            0.033234     1.229644       1.229644    6.347624
Williamtown        54.968428     4.519774       4.486540    2.891326
Witchcliffe       100.000000     1.129944       1.096710    8.308408
Wollongong        100.000000     1.578947       1.578947    4.111842
Woomera            33.300100     1.296112       1.296112    0.963775

                  WindDir3pm  ...  Humidity9am  Humidity3pm  Pressure9am  \
Location                      ...
Adelaide            0.501096  ...     0.156593     0.156593     0.250548
Albany             25.756579  ...     1.611842    23.552632     0.822368
Albury              1.513158  ...     0.296053     0.263158     0.164474
AliceSprings        0.131579  ...     0.098684     0.164474     0.032895
BadgerysCreek       2.824859  ...     1.794616     1.827850     5.583250
Ballarat            0.592105  ...     0.690789     0.230263     0.789474
Bendigo             1.414474  ...     0.230263     0.065789     0.493421
Brisbane            1.064829  ...     0.125274     0.469778     0.031319
Cairns              0.131579  ...     0.032895     0.000000     0.032895
Canberra            6.635623  ...     1.833527     0.349243     6.577416
Cobar               0.498504  ...     4.154204     4.154204     0.997009
CoffsHarbour       10.069791  ...     0.631439     0.731140    10.335660
Dartmoor            3.256896  ...     7.577268     7.477567     2.126952
Darwin              0.093956  ...     0.031319     0.062637     0.031319
GoldCoast           1.151316  ...     0.460526     0.394737     0.032895
Hobart              0.626370  ...     0.313185     0.407141     0.031319
Katherine           1.140684  ...     5.133080    52.978454     0.063371
Launceston          1.842105  ...     0.197368     0.328947    37.927632
Melbourne           0.375822  ...    15.095521    15.252114    15.032884
MelbourneAirport    0.432037  ...     0.265869     0.299103     0.000000
Mildura             0.299103  ...     0.099701     0.132935     0.132935
Moree               1.827850  ...     0.132935     0.166168     0.000000
MountGambier        0.592105  ...     0.394737     0.328947     0.065789
MountGinini         7.631579  ...    14.342105    10.230263   100.000000
Newcastle          43.402435  ...     7.864429    30.865416   100.000000
Nhil                0.316857  ...     0.316857     0.316857     0.316857
NorahHead           1.597870  ...     1.331558     1.065246     1.131824
NorfolkIsland       0.166168  ...     0.166168     0.066467     0.265869
Nuriootpa           1.129944  ...     0.332336     0.432037     0.232635
PearceRAAF          0.897308  ...     0.664673     0.897308     0.697906
Penrith             2.435012  ...     3.158934     2.270484   100.000000
Perth               0.219230  ...     0.281867     0.250548     0.031319
PerthAirport        0.033234  ...     0.000000     0.033234     0.066467
Portland            0.166168  ...     1.628448     0.432037     0.398804
Richmond            3.855101  ...     1.960784     1.994018     0.963775
Sale                0.531738  ...     0.631439     0.498504     0.465271
SalmonGums          2.599134  ...     1.199600     1.199600   100.000000
Sydney              0.986842  ...     0.448565     0.388756     0.627990
SydneyAirport       0.132935  ...     0.066467     0.132935     0.265869
Townsville          0.032895  ...     0.000000     0.000000     0.000000
Tuggeranong         1.546561  ...     0.658111     0.427772     0.493583
Uluru               2.091255  ...     0.950570     0.253485     0.633714
WaggaWagga          0.498504  ...     0.099701     0.000000     0.000000
Walpole             2.727878  ...     2.095808     1.996008     0.931470
Watsonia            1.163177  ...     0.465271     0.000000     0.066467
Williamtown         0.598205  ...     0.265869     0.232635     0.398804
Witchcliffe         0.631439  ...     7.976072     7.776670     4.453307
Wollongong          1.315789  ...     0.953947     0.986842     1.644737
Woomera             0.598205  ...     0.432037     0.897308     0.365570

                  Pressure3pm    Cloud9am    Cloud3pm    Temp9am    Temp3pm  \
Location
Adelaide             0.219230  100.000000  100.000000   0.156593   0.125274
Albany               0.822368    1.250000   23.388158   1.282895  23.421053
Albury               0.263158   57.598684   53.059211   0.296053   0.263158
AliceSprings         0.098684   10.986842   11.875000   0.000000   0.065789
BadgerysCreek        5.749418  100.000000  100.000000   1.362579   1.462280
Ballarat             0.855263   17.960526   34.473684   0.394737   0.197368
Bendigo              0.328947   31.842105   25.394737   0.098684   0.065789
Brisbane             0.250548    0.031319    0.062637   0.125274   0.469778
Cairns               0.000000    6.809211    7.565789   0.032895   0.000000
Canberra             6.431898   31.199069   36.757858   0.523865   0.203725
Cobar                0.864074   12.628780   10.235959   0.265869   0.232635
CoffsHarbour        10.368893   27.018943   25.855766   0.498504   0.465271
Dartmoor             2.160186  100.000000  100.000000   2.160186   2.126952
Darwin               0.062637    0.031319    0.093956   0.000000   0.062637
GoldCoast            0.032895  100.000000  100.000000   0.032895   0.032895
Hobart               0.031319   36.423426   36.580019   0.031319   0.062637
Katherine            0.316857    2.598226   45.880862   2.661597  45.880862
Launceston          37.927632   76.151316   75.592105   0.197368   0.328947
Melbourne           15.126840   32.383339   34.638271  15.064203  15.158158
MelbourneAirport     0.000000    0.000000    0.033234   0.000000   0.000000
Mildura              0.066467    2.791625    4.918578   0.033234   0.033234
Moree                0.033234   17.879694   13.426388   0.000000   0.000000
MountGambier         0.164474    3.618421    3.618421   0.065789   0.164474
MountGinini        100.000000  100.000000  100.000000  13.782895   9.703947
Newcastle          100.000000    7.930240   30.700888   7.699901  30.667983
Nhil                 0.316857  100.000000  100.000000   0.316857   0.316857
NorahHead            0.865513  100.000000  100.000000   1.331558   1.031957
NorfolkIsland        0.066467    2.193420    2.027252   0.166168   0.066467
Nuriootpa            0.265869    4.220671   25.556663   0.166168   0.232635
PearceRAAF           0.930542   34.662679   37.487537   0.598205   0.864074
Penrith            100.000000  100.000000  100.000000   1.283317   0.658111
Perth                0.031319    0.062637    0.125274   0.000000   0.031319
PerthAirport         0.033234    0.066467    0.132935   0.000000   0.033234
Portland             0.332336   13.692257   17.248255   1.595214   0.398804
Richmond             1.163177   79.893652   80.658026   1.329345   1.395813
Sale                 0.498504   11.897640   13.027584   0.066467   0.033234
SalmonGums         100.000000  100.000000  100.000000   1.199600   1.199600
Sydney               0.568182   16.985646   16.836124   0.149522   0.119617
SydneyAirport        0.099701    0.132935    0.000000   0.033234   0.033234
Townsville           0.000000    5.723684    9.111842   0.000000   0.000000
Tuggeranong          0.361961  100.000000  100.000000   0.658111   0.427772
Uluru                0.253485   77.946768   73.574144   0.950570   0.253485
WaggaWagga           0.000000    7.411100    5.749418   0.000000   0.000000
Walpole              0.864937  100.000000  100.000000   0.931470   0.864937
Watsonia             0.000000    0.000000    0.033234   0.465271   0.000000
Williamtown          0.365570   20.006647   21.568627   0.166168   0.066467
Witchcliffe          4.453307  100.000000  100.000000   0.132935   0.066467
Wollongong           0.625000   55.756579   53.388158   0.953947   0.953947
Woomera              0.465271   12.429379   21.900964   0.033234   0.099701

                  RainToday  RainTomorrow
Location
Adelaide           3.194488      3.225806
Albany             0.789474      0.789474
Albury             0.953947      0.953947
AliceSprings       0.263158      0.296053
BadgerysCreek      2.691924      2.691924
Ballarat           0.394737      0.394737
Bendigo            0.197368      0.197368
Brisbane           1.002192      1.002192
Cairns             1.710526      1.710526
Canberra           0.523865      0.523865
Cobar              0.697906      0.697906
CoffsHarbour       1.861083      1.861083
Dartmoor           2.226653      2.193420
Darwin             0.000000      0.031319
GoldCoast          1.973684      1.973684
Hobart             0.156593      0.156593
Katherine          1.140684      1.204056
Launceston         0.394737      0.394737
Melbourne         23.739430     23.739430
MelbourneAirport   0.000000      0.000000
Mildura            0.066467      0.066467
Moree              5.151213      5.151213
MountGambier       0.296053      0.328947
MountGinini        4.375000      4.375000
Newcastle          2.764067      2.764067
Nhil               0.570342      0.570342
NorahHead          2.496671      2.496671
NorfolkIsland      1.495513      1.495513
Nuriootpa          0.199402      0.232635
PearceRAAF         8.208707      8.208707
Penrith            2.467917      2.467917
Perth              0.000000      0.000000
PerthAirport       0.000000      0.000000
Portland           0.432037      0.432037
Richmond           1.927551      1.927551
Sale               0.299103      0.299103
SalmonGums         1.532822      1.532822
Sydney             0.209330      0.209330
SydneyAirport      0.132935      0.132935
Townsville         0.230263      0.230263
Tuggeranong        1.349128      1.349128
Uluru              3.548796      3.612167
WaggaWagga         1.096710      1.096710
Walpole            6.220892      6.220892
Watsonia           0.332336      0.332336
Williamtown       15.154536     15.154536
Witchcliffe        1.894317      1.894317
Wollongong         1.907895      1.875000
Woomera            0.598205      0.631439

[49 rows x 22 columns]
['Adelaide', 'Albany', 'Albury', 'BadgerysCreek', 'Ballarat', 'Bendigo', 'Cobar', 'Dartmoor', 'GoldCoast', 'Katherine', 'Launceston', 'MountGinini', 'Newcastle', 'Nhil', 'NorahHead', 'PearceRAAF', 'Penrith', 'Richmond', 'SalmonGums', 'Tuggeranong', 'Uluru', 'Walpole', 'Witchcliffe', 'Wollongong']
Number of locations with high missing values: 24
Number of rows with high missing values: 68429

In [16]:
#inspection table to show why each location was deleted
high_missing_details = missing_percent_by_location.loc[
    high_missing_locations
]

high_missing_details = high_missing_details.loc[
    :,
    (high_missing_details > 70).any()
]

print(high_missing_details.round(2))

               Evaporation  Sunshine  WindGustDir  WindGustSpeed  Pressure9am  \
Location
Adelaide             46.63     44.60         0.81           0.81         0.25
Albany                9.54     17.11       100.00         100.00         0.82
Albury              100.00    100.00         1.05           1.05         0.16
BadgerysCreek       100.00    100.00         2.53           2.53         5.58
Ballarat            100.00    100.00         1.02           1.02         0.79
Bendigo              61.02    100.00         1.35           1.32         0.49
Cobar                11.40     81.72         1.40           1.40         1.00
Dartmoor             13.59     14.72         2.29           2.29         2.13
GoldCoast           100.00    100.00         3.95           3.95         0.03
Katherine             5.89    100.00         1.84           1.84         0.06
Launceston           95.36    100.00         1.12           1.09        37.93
MountGinini         100.00    100.00        10.49          10.49       100.00
Newcastle           100.00    100.00       100.00         100.00       100.00
Nhil                100.00    100.00         0.70           0.70         0.32
NorahHead           100.00    100.00         1.80           1.80         1.13
PearceRAAF          100.00      0.17         4.82           4.82         0.70
Penrith             100.00    100.00         2.14           2.14       100.00
Richmond             46.03    100.00         1.89           1.83         0.96
SalmonGums          100.00    100.00         2.80           2.80       100.00
Tuggeranong         100.00    100.00         1.38           1.38         0.49
Uluru               100.00    100.00         3.42           3.42         0.63
Walpole             100.00    100.00         3.93           2.86         0.93
Witchcliffe         100.00    100.00         1.13           1.10         4.45
Wollongong          100.00    100.00         1.58           1.58         1.64

               Pressure3pm  Cloud9am  Cloud3pm
Location
Adelaide              0.22    100.00    100.00
Albany                0.82      1.25     23.39
Albury                0.26     57.60     53.06
BadgerysCreek         5.75    100.00    100.00
Ballarat              0.86     17.96     34.47
Bendigo               0.33     31.84     25.39
Cobar                 0.86     12.63     10.24
Dartmoor              2.16    100.00    100.00
GoldCoast             0.03    100.00    100.00
Katherine             0.32      2.60     45.88
Launceston           37.93     76.15     75.59
MountGinini         100.00    100.00    100.00
Newcastle           100.00      7.93     30.70
Nhil                  0.32    100.00    100.00
NorahHead             0.87    100.00    100.00
PearceRAAF            0.93     34.66     37.49
Penrith             100.00    100.00    100.00
Richmond              1.16     79.89     80.66
SalmonGums          100.00    100.00    100.00
Tuggeranong           0.36    100.00    100.00
Uluru                 0.25     77.95     73.57
Walpole               0.86    100.00    100.00
Witchcliffe           4.45    100.00    100.00
Wollongong            0.62     55.76     53.39

In [17]:
original_rows = len(df_raw)

df_clean = df_raw[
    ~df_raw["Location"].isin(high_missing_locations)
].copy()

rows_removed = original_rows - len(df_clean)

print("Original rows:", original_rows)
print("Rows removed:", rows_removed)
print("Remaining rows:", len(df_clean))
print("Percentage removed:", round(rows_removed / original_rows * 100, 2))

Original rows: 145460
Rows removed: 68429
Remaining rows: 77031
Percentage removed: 47.04

In [18]:
missing_after_cleaning = pd.DataFrame({
    "Missing Values": df_clean.isnull().sum(),
    "Missing Percentage": (df_clean.isnull().mean() * 100).round(2)
})

missing_after_cleaning = missing_after_cleaning[
    missing_after_cleaning["Missing Values"] > 0
].sort_values("Missing Percentage", ascending=False)

print(missing_after_cleaning)

               Missing Values  Missing Percentage
Sunshine                11815               15.34
Cloud3pm                 9645               12.52
Evaporation              8516               11.06
Cloud9am                 8269               10.73
WindDir9am               2788                3.62
WindGustDir              2716                3.53
WindGustSpeed            2690                3.49
RainTomorrow             1708                2.22
Rainfall                 1703                2.21
RainToday                1703                2.21
Pressure9am              1126                1.46
Pressure3pm              1122                1.46
WindDir3pm                895                1.16
Humidity9am               757                0.98
Humidity3pm               687                0.89
WindSpeed9am              675                0.88
WindSpeed3pm              665                0.86
Temp9am                   609                0.79
MinTemp                   559                0.73
Temp3pm                   566                0.73
MaxTemp                   548                0.71

#Trying to remove values that are only fully missing

In [19]:
#realoding the orginal dataset staritng fresh
df_clean = df_raw.copy(deep=True)

print("original Set:", df_clean.shape)

original Set: (145460, 23)

In [20]:
empty_columns = df_clean.columns[
    df_clean.isnull().mean() == 1
].tolist()

print("100% missing columns:", empty_columns)

df_clean = df_clean.drop(columns=empty_columns)

100% missing columns: []

In [21]:
empty_rows = df_clean.isnull().all(axis=1)

print("100% missing rows:", empty_rows.sum())

df_clean = df_clean.loc[~empty_rows].copy()

100% missing rows: 0

In [22]:
print("Shape after removing completely empty data:", df_clean.shape)

Shape after removing completely empty data: (145460, 23)

#Task 3- Criteria 1

In [24]:
#Checking missing values 
df_clean = df_raw.copy(deep=True)

#Removig rows with missing targets

df_clean = df_clean.dropna(subset=["RainTomorrow"]).copy()

print("Missing RainTomorrow values:")
print(df_clean["RainTomorrow"].isna().sum())

print("Rows remaining:")
print(df_clean.shape[0])

Missing RainTomorrow values:
0
Rows remaining:
142193

In [25]:
#Rechecing the missing percetnages
missing_percentage = (
    df_clean.isna().mean() * 100
).sort_values(ascending=False)

print(
    missing_percentage[
        missing_percentage > 0
    ]
)

Sunshine         47.692924
Evaporation      42.789026
Cloud3pm         40.152469
Cloud9am         37.735332
Pressure9am       9.855619
Pressure3pm       9.832411
WindDir9am        7.041838
WindGustDir       6.561504
WindGustSpeed     6.519308
WindDir3pm        2.656952
Humidity3pm       2.538803
Temp3pm           1.917113
WindSpeed3pm      1.849599
Humidity9am       1.247600
Rainfall          0.988797
RainToday         0.988797
WindSpeed9am      0.948007
Temp9am           0.635756
MinTemp           0.447983
MaxTemp           0.226453
dtype: float64

In [27]:
#Median filling the lower missing columns
numeric_fill_cols = [
    "MinTemp",
    "MaxTemp",
    "Rainfall",
    "WindGustSpeed",
    "WindSpeed9am",
    "WindSpeed3pm",
    "Humidity9am",
    "Humidity3pm",
    "Pressure9am",
    "Pressure3pm",
    "Temp9am",
    "Temp3pm"
]

for col in numeric_fill_cols:
    df_clean[col] = df_clean[col].fillna(
        df_clean[col].median()
    )

In [28]:
#inspecting missing columns
high_missing_cols = [
    "Sunshine",
    "Evaporation",
    "Cloud9am",
    "Cloud3pm"
]

print(
    df_clean[high_missing_cols]
    .isna()
    .mean()
    .mul(100)
    .round(2)
)

Sunshine       47.69
Evaporation    42.79
Cloud9am       37.74
Cloud3pm       40.15
dtype: float64

In [29]:
#Cleaning the duplicate
duplicates_before = df_clean.duplicated().sum()

df_clean = df_clean.drop_duplicates()

duplicates_after = df_clean.duplicated().sum()

print("Duplicates before cleaning:", duplicates_before)
print("Duplicates after cleaning:", duplicates_after)

Duplicates before cleaning: 0
Duplicates after cleaning: 0

In [31]:
#Incorrect Data types
print(df_clean.dtypes)

df_clean["Date"] = pd.to_datetime(
    df_clean["Date"]
)

print(df_clean["Date"].dtype)

df_clean.info()

Date             datetime64[us]
Location                    str
MinTemp                 float64
MaxTemp                 float64
Rainfall                float64
Evaporation             float64
Sunshine                float64
WindGustDir                 str
WindGustSpeed           float64
WindDir9am                  str
WindDir3pm                  str
WindSpeed9am            float64
WindSpeed3pm            float64
Humidity9am             float64
Humidity3pm             float64
Pressure9am             float64
Pressure3pm             float64
Cloud9am                float64
Cloud3pm                float64
Temp9am                 float64
Temp3pm                 float64
RainToday                   str
RainTomorrow                str
dtype: object
datetime64[us]
<class 'pandas.DataFrame'>
Index: 142193 entries, 0 to 145458
Data columns (total 23 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Date           142193 non-null  datetime64[us]
 1   Location       142193 non-null  str
 2   MinTemp        142193 non-null  float64
 3   MaxTemp        142193 non-null  float64
 4   Rainfall       142193 non-null  float64
 5   Evaporation    81350 non-null   float64
 6   Sunshine       74377 non-null   float64
 7   WindGustDir    132863 non-null  str
 8   WindGustSpeed  142193 non-null  float64
 9   WindDir9am     132180 non-null  str
 10  WindDir3pm     138415 non-null  str
 11  WindSpeed9am   142193 non-null  float64
 12  WindSpeed3pm   142193 non-null  float64
 13  Humidity9am    142193 non-null  float64
 14  Humidity3pm    142193 non-null  float64
 15  Pressure9am    142193 non-null  float64
 16  Pressure3pm    142193 non-null  float64
 17  Cloud9am       88536 non-null   float64
 18  Cloud3pm       85099 non-null   float64
 19  Temp9am        142193 non-null  float64
 20  Temp3pm        142193 non-null  float64
 21  RainToday      140787 non-null  str
 22  RainTomorrow   142193 non-null  str
dtypes: datetime64[us](1), float64(16), str(6)
memory usage: 26.0 MB

In [ ]:
#Inconsistent categories and Formatting
categorical_cols = [
    "Location",
    "WindGustDir",
    "WindDir9am",
    "WindDir3pm",
    "RainToday",
    "RainTomorrow"
]

for col in categorical_cols:
    print("\n", col)
    print(df_clean[col].value_counts(dropna=False))

for col in categorical_cols:
    df_clean[col] = df_clean[col].str.strip()

In [33]:
#Invalid Values
numeric_cols = df_clean.select_dtypes(
    include="number"
).columns

print(
    df_clean[numeric_cols]
    .agg(["min", "max"])
    .T
)

                 min     max
MinTemp         -8.5    33.9
MaxTemp         -4.8    48.1
Rainfall         0.0   371.0
Evaporation      0.0   145.0
Sunshine         0.0    14.5
WindGustSpeed    6.0   135.0
WindSpeed9am     0.0   130.0
WindSpeed3pm     0.0    87.0
Humidity9am      0.0   100.0
Humidity3pm      0.0   100.0
Pressure9am    980.5  1041.0
Pressure3pm    977.1  1039.6
Cloud9am         0.0     9.0
Cloud3pm         0.0     9.0
Temp9am         -7.2    40.2
Temp3pm         -5.4    46.7

In [32]:
invalid_humidity = df_clean[
    (df_clean["Humidity9am"] < 0)
    | (df_clean["Humidity9am"] > 100)
    | (df_clean["Humidity3pm"] < 0)
    | (df_clean["Humidity3pm"] > 100)
]

print("Invalid humidity rows:")
print(invalid_humidity.shape[0])

Invalid humidity rows:
0

In [34]:
invalid_humidity = df_clean[
    (df_clean["Humidity9am"] < 0)
    | (df_clean["Humidity9am"] > 100)
    | (df_clean["Humidity3pm"] < 0)
    | (df_clean["Humidity3pm"] > 100)
]

print("Invalid humidity rows:")
print(invalid_humidity.shape[0])

Invalid humidity rows:
0

In [35]:
wind_cols = [
    "WindGustSpeed",
    "WindSpeed9am",
    "WindSpeed3pm"
]

for col in wind_cols:
    print(
        col,
        "negative values:",
        (df_clean[col] < 0).sum()
    )

WindGustSpeed negative values: 0
WindSpeed9am negative values: 0
WindSpeed3pm negative values: 0

In [37]:
#Rrrunning all the code to see changes actually worked
print("Cleaned shape:")
print(df_clean.shape)

print("\nMissing values:")
print(
    df_clean.isna()
    .sum()
    .loc[lambda x: x > 0]
    .sort_values(ascending=False)
)

print("\nDuplicate rows:")
print(df_clean.duplicated().sum())

print("\nData types:")
print(df_clean.dtypes)


df_clean = df_clean.reset_index(drop=True)

Cleaned shape:
(142193, 23)

Missing values:
Sunshine       67816
Evaporation    60843
Cloud3pm       57094
Cloud9am       53657
WindDir9am     10013
WindGustDir     9330
WindDir3pm      3778
RainToday       1406
dtype: int64

Duplicate rows:
0

Data types:
Date             datetime64[us]
Location                    str
MinTemp                 float64
MaxTemp                 float64
Rainfall                float64
Evaporation             float64
Sunshine                float64
WindGustDir                 str
WindGustSpeed           float64
WindDir9am                  str
WindDir3pm                  str
WindSpeed9am            float64
WindSpeed3pm            float64
Humidity9am             float64
Humidity3pm             float64
Pressure9am             float64
Pressure3pm             float64
Cloud9am                float64
Cloud3pm                float64
Temp9am                 float64
Temp3pm                 float64
RainToday                   str
RainTomorrow                str
dtype: object